version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci # release-please groups these under "CI"
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: deps # release-please groups these under "Dependencies"
    groups:
      python-tooling:
        patterns: ["*"]
